#!/bin/sh

set -e

mkdir -p /var/lib/mysql /run/mysqld

chown -R mysql:mysql /var/lib/mysql /run/mysqld

openrc
touch /run/openrc/softlevel

/etc/init.d/mariadb setup

sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf
sed -i "s/\bskip-networking\b/port=3306/g" /etc/my.cnf.d/mariadb-server.cnf

rc-service mariadb start

mariadb -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
mariadb -e "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';"
mariadb -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';"
mariadb -e "FLUSH PRIVILEGES;"
mariadb -e "USE mysql; ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWORD';"

rc-service mariadb stop

exec $@