#!/bin/sh

set -e

echo "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;" | mysql
echo "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" | mysql
echo "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';" | mysql
echo "FLUSH PRIVILEGES;" | mysql
# echo "use mysql;UPDATE user SET Password=PASSWORD('toor') WHERE user='root'; \
#         UPDATE user SET plugin = '' WHERE user = 'root';FLUSH PRIVILEGES;" | mysql
