version: '3'

services:
# ---------------------------- nginx ---------------------------- #
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    image: nginxi
    ports:
      - 8080:80
    hostname: nginx
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
# -------------------------- wordpress -------------------------- #
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpressi
    hostname: wordpress
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/wordpress/config/php-fpm.conf:/etc/php82/php-fpm.d/www.conf
      - ./requirements/wordpress/config/wp-config.php:/var/www/wordpress/wp-config.php
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
# -------------------------- mariadb --------------------------- #
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadbi
    hostname: mariadb
    networks:
      - inception
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    command: "/startup"
    volumes:
      - maria:/var/lib/mysql
# ----------------------- shared network ----------------------- #
networks:
  inception:
    driver: bridge

volumes:
  wp:
  maria: