version: '3'

services:
# ---------------------------- nginx ---------------------------- #
  server:
    depends_on:
      - web
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 8888:80
    hostname: nginx
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/nginx/config/server.conf:/etc/nginx/http.d/default.conf
    restart: unless-stopped
# -------------------------- wordpress -------------------------- #
  web:
    depends_on:
      - db
    build: ./requirements/wordpress/
    container_name: wordpress
    hostname: wordpress
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/wordpress/config/php-fpm.conf:/etc/php81/php-fpm.d/www.conf
      - ./requirements/wordpress/config/wp-config.php:/var/www/wordpress/wp-config.php
    # restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db
# -------------------------- mariadb --------------------------- #
  db:
    build: ./requirements/mariadb/
    container_name: mariadb
    hostname: mariadb
    networks:
      - inception
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
# ----------------------- shared network ----------------------- #
networks:
  inception:
    driver: bridge

volumes:
  wp:
  database: