version: '3'

services:
# ---------------------------- nginx ---------------------------- #
  server:
    depends_on:
      - web
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/nginx/config/server.conf:/etc/nginx/http.d/default.conf
    env_file:
      - .env
    restart: unless-stopped
# -------------------------- wordpress -------------------------- #
  web:
    depends_on:
      - db
      - redis
    build: ./requirements/wordpress/
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/wordpress/config/php-fpm.conf:/etc/php81/php-fpm.d/www.conf
    env_file:
      - .env
    restart: unless-stopped
# -------------------------- mariadb --------------------------- #
  db:
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    container_name: mariadb
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    restart: unless-stopped
# ----------------------------  redis -------------------------- #
  redis:
    build: ./requirements/redis
    container_name: redis
    networks:
      - inception
    expose:
      - 6379
    restart: unless-stopped
# ----------------------------  FTP -------------------------- #
  ftp_server:
    build:
      context: ./requirements/ftp
      args:
        FTP_ADMIN_PASSWD: ${FTP_ADMIN_PASSWD}
        FTP_USER_PASSWD: ${FTP_USER_PASSWD}
    container_name: ftp_server
    ports:
      - 20:20
      - 21:21
      - 5000-10000:5000-10000
    networks:
      - inception
    restart: unless-stopped
# ----------------------- shared network ----------------------- #
networks:
  inception:
    driver: bridge

volumes:
  wp:
  database:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: ${HOME}/data/wordpress
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: ${HOME}/data/mariadb