version: '3'

services:
# ---------------------------- nginx ---------------------------- #
  server:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./requirements/nginx/ssl/server.key:/etc/nginx/ssl/server.key
      # - ./requirements/nginx/config/server.conf:/etc/nginx/http.d/default.conf
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - web
      - redis
      - ftp_server
# -------------------------- wordpress -------------------------- #
  web:
    build: ./requirements/wordpress/
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/wordpress/config/php-fpm.conf:/etc/php81/php-fpm.d/www.conf
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - ftp_server
# -------------------------- mariadb --------------------------- #
  db:
    build: ./requirements/mariadb/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    restart: unless-stopped
# ----------------------------  redis -------------------------- #
  redis:
    build: ./requirements/redis
    container_name: redis
    networks:
      - inception
    expose:
      - 6379
    restart: unless-stopped
# ----------------------------  FTP -------------------------- #
  ftp_server:
    build:
      context: ./requirements/ftp
      args:
        FTP_ADMIN_PASSWD: ${FTP_ADMIN_PASSWD}
        FTP_USER_PASSWD: ${FTP_USER_PASSWD}
    container_name: ftp_server
    ports:
      - 21:21
      - 30000-30019:30000-30019
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
# ------------------------ Static site ------------------------- #
  static:
    build: ./requirements/static
    container_name: static
    ports:
      - 8080:80
    networks:
      - inception
    restart: unless-stopped
# ------------------------ Prometheus ------------------------- #
  locust:
    build: ./requirements/locust/
    container_name: locust
    networks:
      - inception
    volumes:
      - ./requirements/locust/src/locustfile.py:/mnt/locust/locustfile.py
    ports:
      - 8089:8089
# ----------------------- Adminer ----------------------- #
  adminer:
    build: ./requirements/adminer
    container_name: adminer
    networks:
      - inception
    ports:
      - 3000:3000
# ----------------------- shared network ----------------------- #
networks:
  inception:

volumes:
  wp:
  database:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: ${HOME}/data/wordpress
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: ${HOME}/data/mariadb