version: '3'

services:
# ---------------------------- nginx ---------------------------- #
  server:
    depends_on:
      - web
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 8888:80
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/nginx/config/server.conf:/etc/nginx/http.d/default.conf
    restart: unless-stopped
# -------------------------- wordpress -------------------------- #
  web:
    depends_on:
      - db
    build: ./requirements/wordpress/
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
      - ./requirements/wordpress/config/php-fpm.conf:/etc/php81/php-fpm.d/www.conf
      - ./requirements/wordpress/config/wp-config.php:/var/www/wordpress/wp-config.php
    restart: unless-stopped
# -------------------------- mariadb --------------------------- #
  db:
    build:
      context: ./requirements/mariadb/
      args:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: mariadb
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
# ----------------------- shared network ----------------------- #
networks:
  inception:
    driver: bridge

volumes:
  wp:
  database: