version: '3'

services:
# ---------------------------- nginx ---------------------------- #
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    image: nginxi
    ports:
      - 8080:80
    hostname: nginx
    networks:
      - inception
    volumes:
      - ./requirements/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/wordpress/wordpress:/var/www/html
    restart: unless-stopped
# -------------------------- wordpress -------------------------- #
  wordpress:
    # depends_on:
    #   - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpressi
    hostname: wordpress
    networks:
      - inception
    volumes:
      - ./requirements/wordpress/wordpress:/var/www/html
      - ./requirements/wordpress/config/php-fpm.conf:/etc/php81/php-fpm.d/www.conf
    restart: unless-stopped
    # env_file: .env
    # environment:
    #   - WORDPRESS_DB_HOST=mariadb:3306
    #   - WORDPRESS_DB_USER=$MYSQL_USER
    #   - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    #   - WORDPRESS_DB_NAME=wordpress
# -------------------------- mariadb --------------------------- #
# ----------------------- shared network ----------------------- #
networks:
  inception:
    name: inception
    driver: bridge
