#!/bin/ash

echo "bind-address = 0.0.0.0" >> /etc/my.cnf

echo "port = 3306" >> /etc/my.cnf

/usr/bin/mysql_install_db --user=mysql --datadir=/var/lib/mysql

mariadbd --user=root

# /usr/bin/mysqld_safe --datadir="/var/lib/mysql"
