#!/bin/sh
set -e

wp core download --path=/var/www/wordpress --force

wp config create --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASSWORD \
				--dbhost=$DB_HOST --dbprefix=utf8 --force

wp core install \
    --url="$URL" \
    --title="$TITLE" \
    --admin_user="$ADMIN_USER" \
    --admin_password="$ADMIN_PASSWORD" \
    --admin_email="$ADMIN_EMAIL" \
    --skip-email

adduser -S -u 1000 -G www-data www-data

find /var/www/ -type d -exec chmod 755 {} \;

find /var/www/ -type f -exec chmod 644 {} \;

chown -R www-data:www-data /var/www/

exec $@
