#!/bin/sh

set -e

wp core download --path=/var/www/wordpress --force

# wp config create --dbname=db --dbuser=user --dbpass=password --force

# echo "define('DB_SOCKET', 'mariadb:3306');" >> /var/www/wordpress/wp-config.php



WP_URL="http://localhost:8888"
WP_TITLE="WORDPRESS"
ADMIN_USER="admin"
ADMIN_PASSWORD="admin"
ADMIN_EMAIL="admin@example.com"


wp core install \
    --url="$WP_URL" \
    --title="$WP_TITLE" \
    --admin_user="$ADMIN_USER" \
    --admin_password="$ADMIN_PASSWORD" \
    --admin_email="$ADMIN_EMAIL" \
    --skip-email

adduser -S -u 1000 -G www-data www-data

find /var/www/ -type d -exec chmod 755 {} \;

find /var/www/ -type f -exec chmod 644 {} \;

chown -R www-data:www-data /var/www/

echo "OK"

exec $@
