#!/bin/sh
set -e

wp config create --dbname="$DB_NAME" --dbuser="$DB_USER" --dbpass="$DB_PASSWORD" \
                  --dbhost="$WP_DB_HOST" --dbprefix=wp_ --force


wp core install --url="$WP_URL" --title="$WP_TITLE" --admin_user="$WP_ADMIN_USER" \
                --admin_password="$WP_ADMIN_PASSWORD" --admin_email="$WP_ADMIN_EMAIL" --skip-email

wp config set WP_REDIS_HOST "redis"
wp config set WP_REDIS_PORT "6379"

wp plugin install redis-cache --activate

if ! wp user get regular --field=user_login 2> /dev/null; then
    wp user create regular regular@example.com --role=author --user_pass="regular" --display_name="Regular user"
else
    echo "User 'regular' already exists."
fi

find /var/www/ -type d -exec chmod 755 {} \;
find /var/www/ -type f -exec chmod 644 {} \;
chown -R www:www /var/www/

exec $@
